{
 "title": "Vehicle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Video Feed",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AVG Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bus",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "query": "SELECT  max(\"busses\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "cars" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "busses" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "bikes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Cars",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"cars\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "BIkes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"bikes\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(10s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Access Control Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "bbox_data",
     "query": "SELECT max(\"in_zone\") FROM \"bbox_data\" WHERE ((\"class_name\" = '2') or \"class_name\" = '3' or \"class_name\" = '5') AND $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "in_zone" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "class_name", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Cars",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "query": "SELECT max(\"cars\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "cars" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "query": "SELECT max(\"busses\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(6s) fill(0)",
     "select": [
      [
       { "params": [ "busses" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "select": [
      [
       { "params": [ "cars" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Cars" ], "type": "alias" }
      ],
      [
       { "params": [ "bikes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Bikes" ], "type": "alias" }
      ],
      [
       { "params": [ "busses" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Busses" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frame Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Postprocess",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "postprocess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Decode",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "decode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Inference",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "inference" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Preprocess",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "preprocess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Render",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "render" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 } },
  {
   "title": "FPS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "model_latency",
     "select": [
      [
       { "params": [ "info_fps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bikes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "select": [
      [
       { "params": [ "bikes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "car_count",
     "query": "SELECT max(\"bikes\")+max(\"cars\")+max(\"busses\") FROM \"car_count\" WHERE $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "bikes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}